title: Edusemi
description: 教育ポータル

markdown: kramdown
theme: null         # ← Jekyllテーマを無効化
exclude:            # ← Jekyllが処理しないファイル・フォルダ
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

permalink: pretty   # ← .html拡張子をURLから省略
