title: Edusemi
description: 教育ポータル

markdown: kramdown
theme: minima        # ✅ Jekyll公式テーマ「minima」を有効化

exclude:             # ✅ Jekyllが処理対象外とするファイル・フォルダ
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

permalink: pretty    # ✅ URLから .html を省略可能に
