title: Edusemi
description: 教育ポータル

markdown: kramdown
theme: minima

kramdown:
  input: GFM
  parse_block_html: true   # ✅ HTMLタグ（img, div等）を有効化
  hard_wrap: false

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

permalink: pretty
