site_name: Edusemi

theme:
  name: material
  custom_dir: overrides  # ← ここが追加点

markdown_extensions:
  - admonition
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true

# 以下は overrides/main.html に MathJax を記述する場合は不要
# 念のため残しておきたい場合のみ維持してOK（影響なし）
# extra_javascript:
#   - js/mathjax-config.js
#   - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
