- name: Render Mermaid to PNG/SVG
  shell: bash
  run: |
    BASE="d_chapter5a_analog_mixed_signal/paper/figures"
    SRC="$BASE/src"
    PNG="$BASE/png"
    SVG="$BASE/svg"
    mkdir -p "$PNG" "$SVG"
    shopt -s nullglob
    n=0
    for f in "$SRC"/*.mmd; do
      b=$(basename "$f" .mmd)
      echo "Rendering $f"
      mmdc -i "$f" -o "$PNG/${b}.png" -b transparent -w 1600 --puppeteerConfigFile puppeteer-config.json
      mmdc -i "$f" -o "$SVG/${b}.svg" --puppeteerConfigFile puppeteer-config.json
      n=$((n+1))
    done
    echo "Rendered $n files."
