name: Build Figures (Mermaid -> PNG)

on:
  push:
    paths:
      - "paper/figures/src/**.mmd"
      - ".github/workflows/figures.yml"
  workflow_dispatch:

jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install mermaid-cli
        run: |
          npm install -g @mermaid-js/mermaid-cli

      - name: Render Mermaid to PNG
        run: |
          mkdir -p paper/figures/png
          for f in paper/figures/src/*.mmd; do
            base=$(basename "$f" .mmd)
            mmdc -i "$f" -o "paper/figures/png/${base}.png" -b transparent -w 1600
          done

      - name: Commit PNGs
        run: |
          git config user.name "github-actions"
          git config user.email "actions@users.noreply.github.com"
          git add paper/figures/png/*.png || true
          git commit -m "Render Mermaid figures" || echo "No changes"
          git push || true
