- name: Render Mermaid to PNG/SVG
  shell: bash
  run: |
    BASE="d_chapter5a_analog_mixed_signal/paper/figures"
    SRC="$BASE/src"
    PNG="$BASE/png"
    SVG="$BASE/svg"
    mkdir -p "$PNG" "$SVG"
    echo "Listing Mermaid sources in $SRC"
    ls -la "$SRC" || true
    shopt -s nullglob
    n=0
    for f in "$SRC"/*.mmd; do
      base=$(basename "$f" .mmd)
      echo "Rendering $f"
      # PNG 出力
      mmdc -i "$f" -o "$PNG/${base}.png" -b transparent -w 1600 --no-sandbox
      # SVG 出力
      mmdc -i "$f" -o "$SVG/${base}.svg" --no-sandbox
      n=$((n+1))
    done
    echo "Rendered $n files."
