name: Build LaTeX (review_dram_feram)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Tectonic
        uses: wtfjoke/setup-tectonic@v3

      - name: Compile main.tex
        run: |
          tectonic -X compile main.tex --keep-logs

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: review_dram_feram_pdf
          path: main.pdf
